export const SET_SORT = 'SET_SORT';
export const SET_TRANSFER_FILTER = 'SET_TRANSFER_FILTER';
export const SET_STATUS_IS_FETCHING = 'SET_STATUS_IS_FETCHING';
export const SET_SEARCH_ID = 'SET_SEARCH_ID';
export const SET_TICKETS = 'SET_TICKETS';
export const INC_BAD_REQUEST = 'INC_BAD_REQUEST';
export const SET_ERROR_GET_TICKETS = 'SET_ERROR_GET_TICKETS';
